services:
  ratings:
    enabled: true
    image: 293222827824.dkr.ecr.us-east-1.amazonaws.com/roboshop-ratings
    tag: latest
    port: 8080
    replicas: 2
    ingress:
      enabled: false
    dbInit:
      enabled: true
      image: 293222827824.dkr.ecr.us-east-1.amazonaws.com/roboshop-ratings-db
      tag: latest
