apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
data:
  MYSQL_HOST: {{ .Values.db.mysqlHost | quote }}
  DB_HOST: {{ .Values.db.mysqlHost | quote }}
  MONGODB_HOST: {{ .Values.db.mongodbHost | quote }}
  VALKEY_HOST: {{ .Values.db.valkeyHost | quote }}
  REDIS_HOST: {{ .Values.db.valkeyHost | quote }}
  RABBITMQ_HOST: {{ .Values.db.rabbitmqHost | quote }}
  AMQP_HOST: {{ .Values.db.rabbitmqHost | quote }}
  AMQP_USER: "roboshop"
  AMQP_PASS: "RoboShop@1"
  DB_ROOT_PASS: "RoboShop@1"
  PORT: "8080"
  CATALOGUE_HOST: "catalogue.{{ .Values.namespace }}.svc.cluster.local"
  CATALOGUE_URL: "http://catalogue.{{ .Values.namespace }}.svc.cluster.local:8080"
  CART_URL: "http://cart.{{ .Values.namespace }}.svc.cluster.local:8080"
  USER_URL: "http://user.{{ .Values.namespace }}.svc.cluster.local:8080"
  NOTIFICATION_URL: "http://notification.{{ .Values.namespace }}.svc.cluster.local:8080"
  SHIPPING_URL: "http://shipping.{{ .Values.namespace }}.svc.cluster.local:8080"
  USER_HOST: "user.{{ .Values.namespace }}.svc.cluster.local"
  CART_HOST: "cart.{{ .Values.namespace }}.svc.cluster.local"
  SHIPPING_HOST: "shipping.{{ .Values.namespace }}.svc.cluster.local"
  PAYMENT_HOST: "payment.{{ .Values.namespace }}.svc.cluster.local"
  NOTIFICATION_HOST: "notification.{{ .Values.namespace }}.svc.cluster.local"
  ORDERS_HOST: "orders.{{ .Values.namespace }}.svc.cluster.local"
  RATINGS_HOST: "ratings.{{ .Values.namespace }}.svc.cluster.local"
